import { Eye, HandHeart, MapPin, ShieldCheck } from '@phosphor-icons/react'
import { Link, useOutletContext } from 'react-router-dom'
import PageHero from '../components/PageHero.jsx'
import Reveal from '../components/Reveal.jsx'
import ClosingCTA from '../components/ClosingCTA.jsx'
import { ADDRESS, MAP_LINK } from '../data/siteContent.jsx'

export default function AboutPage() {
  const { openRequest } = useOutletContext()
  return (
    <>
      <PageHero title="Local repair with a more considered experience." copy="Max Mobbiles brings clear digital intake to a real store in Vanasthalipuram." action="Plan a store visit" onAction={() => openRequest()} />
      <section className="py-24 sm:py-32"><div className="mx-auto grid max-w-[1240px] gap-14 px-5 sm:px-8 lg:grid-cols-[0.82fr_1.18fr] lg:gap-24"><Reveal><h2 className="section-title">The phone is small. Its role in your day is not.</h2></Reveal><Reveal><p className="text-xl leading-9 text-[#40516a]">A repair counter often begins with one rushed sentence: “It stopped working.” Max Mobbiles is building a better beginning, where customers can organize the symptom before the conversation starts.</p><p className="mt-6 leading-8 text-[#66738a]">This website does not replace hands-on inspection. It makes the handoff more useful by separating known facts, visible symptoms, and decisions that still need a technician.</p></Reveal></div></section>
      <section className="bg-white py-24 sm:py-32"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal className="max-w-3xl"><h2 className="section-title">What guides the experience.</h2><p className="section-copy">The visual polish is only useful when it makes the next action easier to understand.</p></Reveal><div className="mt-14 grid gap-5 lg:grid-cols-12"><Reveal className="rounded-[16px] bg-[#1857d8] p-8 text-white lg:col-span-6 lg:p-11"><Eye size={39} weight="duotone" /><h3 className="mt-12 text-3xl font-[760] tracking-[-0.03em]">Say what is known</h3><p className="mt-4 max-w-[48ch] leading-7 text-[#dce7ff]">Symptoms can be described immediately. Diagnosis, parts, pricing, and timing belong after assessment.</p></Reveal><Reveal className="rounded-[16px] bg-[#eaf1ff] p-8 lg:col-span-3 lg:p-9"><HandHeart size={36} className="text-[#1857d8]" weight="duotone" /><h3 className="mt-10 text-2xl font-[760] tracking-[-0.025em]">Respect the handoff</h3><p className="mt-4 leading-7 text-[#5a6780]">A clear request saves customers from remembering every detail at once.</p></Reveal><Reveal className="rounded-[16px] bg-[#f4f7fb] p-8 lg:col-span-3 lg:p-9"><ShieldCheck size={36} className="text-[#1857d8]" weight="duotone" /><h3 className="mt-10 text-2xl font-[760] tracking-[-0.025em]">Protect expectations</h3><p className="mt-4 leading-7 text-[#5a6780]">Useful guidance avoids promises the physical device has not confirmed.</p></Reveal></div></div></section>
      <section className="py-24 sm:py-32"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal className="max-w-3xl"><h2 className="section-title">A better counter conversation starts with context.</h2><p className="section-copy">The request builder helps turn a rushed explanation into a structured starting point while keeping the important decisions with the technician and customer.</p></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-[16px] bg-[#dce4ef] lg:grid-cols-2"><Reveal className="bg-[#eef3fa] p-8 sm:p-12"><p className="text-sm font-extrabold text-[#1857d8]">What you can prepare</p><ul className="mt-8 space-y-5 text-lg font-bold text-[#263750]"><li>What changed and when</li><li>Which functions still work</li><li>Relevant drops, water, heat, or updates</li><li>The best way to contact you</li></ul></Reveal><Reveal className="bg-white p-8 sm:p-12"><p className="text-sm font-extrabold text-[#1857d8]">What assessment must confirm</p><ul className="mt-8 space-y-5 text-lg font-bold text-[#263750]"><li>The actual cause of the problem</li><li>The suitable repair approach</li><li>Parts availability and scope</li><li>Price and expected timing</li></ul></Reveal></div></div></section>
      <section className="py-24 sm:py-32"><div className="mx-auto grid max-w-[1240px] items-center gap-12 px-5 sm:px-8 lg:grid-cols-2 lg:gap-20"><Reveal className="relative overflow-hidden rounded-[16px] bg-[#eaf1ff] p-9 sm:p-12"><div className="calibration-lines" aria-hidden="true" /><MapPin size={42} className="relative text-[#1857d8]" weight="duotone" /><h2 className="relative mt-12 text-4xl font-[770] tracking-[-0.035em]">Rooted in Vanasthalipuram.</h2><address className="relative mt-5 max-w-[42ch] not-italic leading-8 text-[#56647b]">{ADDRESS}</address><a className="primary-button relative mt-8" href={MAP_LINK} target="_blank" rel="noreferrer">Get directions</a></Reveal><Reveal><h2 className="section-title">Digital clarity, real local service.</h2><p className="section-copy">Use the request builder before visiting, or open the contact page to see the exact location and directions.</p><Link className="secondary-button mt-8" to="/contact">Visit the contact page</Link></Reveal></div></section>
      <ClosingCTA title="Bring a clearer starting point to the counter." copy="Prepare the issue, device, and contact details before your store visit." onAction={() => openRequest()} />
    </>
  )
}
